# Generated by Django 5.0.4 on 2024-04-21 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InviteCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6, unique=True, verbose_name='Код')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=11, unique=True, verbose_name='Номер телефона')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('invited_users', models.ManyToManyField(blank=True, to='users.user', verbose_name='Приглашенные пользователи')),
                ('someone_invite_code', models.ForeignKey(max_length=6, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='code_from_user', to='users.invitecode', verbose_name='Чужой инвайд код')),
            ],
        ),
        migrations.AddField(
            model_name='invitecode',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='code', to='users.user'),
        ),
    ]
