# Generated by Django 5.0.4 on 2024-04-21 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='slug',
        ),
        migrations.AddField(
            model_name='user',
            name='invite_code',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inv_code', to='users.invitecode', verbose_name='Код приглашения'),
        ),
    ]
