# Generated by Django 5.0.4 on 2024-04-22 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_invitecode_user_alter_user_invite_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvitedfUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=11, null=True, unique=True, verbose_name='Номер телефона')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='invite_code',
            field=models.CharField(max_length=6, unique=True, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='user',
            name='someone_invite_code',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True, verbose_name='Код-приглашение от пользователя'),
        ),
        migrations.RemoveField(
            model_name='user',
            name='invited_users',
        ),
        migrations.DeleteModel(
            name='InviteCode',
        ),
        migrations.AddField(
            model_name='user',
            name='invited_users',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='users.invitedfusers', verbose_name='Приглашенные пользователи'),
            preserve_default=False,
        ),
    ]
