# Generated by Django 5.0.4 on 2024-04-22 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_user_invited_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='invited_users',
        ),
        migrations.CreateModel(
            name='InvitedUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invited_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invited_user', to='users.user')),
                ('user_who_invite', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_who_invite', to='users.user')),
            ],
        ),
        migrations.DeleteModel(
            name='InvitedfUsers',
        ),
    ]
