# Generated by Django 5.0.4 on 2024-04-22 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_user_invited_users_invitedusers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='invited_users',
            field=models.ManyToManyField(null=True, related_name='users', through='users.InvitedUsers', to='users.user', verbose_name='Приглашенные пользователи'),
        ),
    ]
