# Generated by Django 5.0.4 on 2024-04-22 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_user_invited_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='someone_invite_code',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Код-приглашение от пользователя'),
        ),
    ]
