# Generated by Django 5.0.4 on 2024-04-23 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_user_someone_invite_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.IntegerField(max_length=11, unique=True, verbose_name='Номер телефона'),
        ),
    ]
