# Generated by Django 5.0.4 on 2024-04-23 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invitedusers',
            options={'verbose_name': 'Приглашенный пользователь', 'verbose_name_plural': 'приглашенные пользователи'},
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.IntegerField(unique=True, verbose_name='Номер телефона'),
        ),
    ]
